# Generated by Django 5.2.4 on 2025-07-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdminChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ImageField(upload_to='')),
                ('name_of_coordinator', models.CharField(max_length=100)),
                ('description_of_coordinator', models.TextField()),
                ('devlopment_team', models.ImageField(upload_to='')),
                ('name_of_team', models.CharField(max_length=100)),
                ('description_of_team', models.TextField()),
                ('project_features', models.TextField()),
            ],
        ),
    ]
