# Generated by Django 5.2.4 on 2025-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0002_homeadminchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coordinators')),
                ('name', models.CharField(max_length=100)),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevlopmentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='devlopment_team')),
                ('name', models.CharField(max_length=100)),
                ('role', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HomeAdminChange',
        ),
    ]
