# Generated by Django 5.2.4 on 2025-07-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0003_coordinator_devlopmentteam_delete_homeadminchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='image',
        ),
        migrations.RemoveField(
            model_name='devlopmentteam',
            name='image',
        ),
    ]
