# Generated by Django 5.2.4 on 2025-07-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0004_remove_coordinator_image_remove_devlopmentteam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coordinators'),
        ),
        migrations.AddField(
            model_name='devlopmentteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devlopment_team'),
        ),
    ]
