# Generated by Django 5.2.4 on 2025-07-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0005_coordinator_image_devlopmentteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coordinators/'),
        ),
        migrations.AlterField(
            model_name='devlopmentteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devlopment_team/'),
        ),
    ]
