# Generated by Django 5.2.4 on 2025-07-30 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0007_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskDoubts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt_name', models.CharField(max_length=500)),
                ('doubt_description', models.TextField(blank=True, null=True)),
                ('subject_select', models.CharField(max_length=300)),
                ('doubt_image', models.ImageField(blank=True, null=True, upload_to='doubt_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
