# Generated by Django 5.2.4 on 2025-07-30 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0008_askdoubts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askdoubts',
            name='teacher_select',
            field=models.ForeignKey(choices=[('python', 'PYTHON'), ('Cloud Cmputing', 'CLOUD COMPUTING'), ('Machine Learning', 'MACHINE LEARNING'), ('C', 'C'), ('Emplyebility Skill', 'EMPLOYBILITY SKILL')], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
