# Generated by Django 5.2.4 on 2025-07-30 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0009_alter_askdoubts_teacher_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='askdoubts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='askdoubts',
            name='teacher_select',
            field=models.CharField(blank=True, choices=[('python', 'PYTHON'), ('Cloud Cmputing', 'CLOUD COMPUTING'), ('Machine Learning', 'MACHINE LEARNING'), ('C', 'C'), ('Emplyebility Skill', 'EMPLOYBILITY SKILL')], max_length=200, null=True),
        ),
    ]
