# Generated by Django 5.2.4 on 2025-08-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0010_askdoubts_user_alter_askdoubts_teacher_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest', models.CharField(blank=True, max_length=500, null=True)),
                ('future_goals', models.CharField(blank=True, max_length=300, null=True)),
                ('about_me', models.CharField(blank=True, max_length=600, null=True)),
                ('Skills', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
