# Generated by Django 5.2.4 on 2025-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
