# Generated by Django 5.2.4 on 2025-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0013_alter_userprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='main_logo/'),
        ),
    ]
