# Generated by Django 5.2.4 on 2025-08-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0014_coordinator_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='logo',
        ),
    ]
