# Generated by Django 5.2.4 on 2025-08-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0015_remove_coordinator_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='main_logo/')),
            ],
        ),
    ]
