# Generated by Django 5.2.4 on 2025-08-17 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0016_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='answer_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='doubt.askdoubts')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
