# Generated by Django 5.2.4 on 2025-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0017_doubtanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtanswer',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
